/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package In_records;

import Classes.AS_prod;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahsan
 */
public class InRecords extends javax.swing.JFrame {

    /**
     * Creates new form Rec_comp_acc
     */
    public InRecords() {
        initComponents();
        
        setCentre();
        
        AS_prod as=new AS_prod();
        caty.setSelectedItem("Total_Record");
        as.InReset(tab_rec1);
        
        Call();
    }
    
    private void setCentre(){
        //to set the jframe on centre:
        Toolkit tool = Toolkit.getDefaultToolkit();
        Dimension dim= new Dimension(tool.getScreenSize());
        int height=(int)dim.getHeight();
        int width=(int)dim.getWidth();
        setLocation(width/ 2-getWidth() / 2,height / 2-getHeight() /2);
    }
    
    private int Tqty(){
        int count=tab_rec1.getRowCount(), sum=0;
        
        for(int i=0; i<count; i++)
            sum=sum+Integer.parseInt(tab_rec1.getValueAt(i, 3).toString());
        
        return sum; 
    }
    
    private int TPtotal(){
        int count=tab_rec1.getRowCount(), sum=0;
        
        for(int i=0; i<count; i++)
            sum=sum+Integer.parseInt(tab_rec1.getValueAt(i, 4).toString());
       
        return sum; 
    }
    
    private int Ttotal(){
        int count=tab_rec1.getRowCount(), sum=0;
        
        for(int i=0; i<count; i++)
            sum=sum+Integer.parseInt(tab_rec1.getValueAt(i, 5).toString());
       
        return sum; 
    }
    
    private void Call(){
        t_total.setText(Integer.toString(Ttotal()));
        t_prod.setText(Integer.toString(tab_rec1.getRowCount()));
        t_qty.setText(Integer.toString(Tqty()));
        t_PUtotal.setText(Integer.toString(TPtotal()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        t_prod = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        t_total = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_qty = new javax.swing.JTextField();
        caty = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        t_PUtotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_rec1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Total Products:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 120, 40));

        t_prod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        t_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_prodActionPerformed(evt);
            }
        });
        getContentPane().add(t_prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 90, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 70, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Total Prices:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 120, 40));

        t_total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        t_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_totalActionPerformed(evt);
            }
        });
        getContentPane().add(t_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 90, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Total Quantities:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 120, 40));

        t_qty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(t_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 90, 40));

        caty.setFont(new java.awt.Font("Trebuchet MS", 3, 26)); // NOI18N
        caty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Total_Record", "Computer_Accessories", "Hardware", "Composing", "Stationary" }));
        getContentPane().add(caty, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 50));

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 100, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Total Unit Prices:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 120, 40));

        t_PUtotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        t_PUtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_PUtotalActionPerformed(evt);
            }
        });
        getContentPane().add(t_PUtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 90, 40));

        tab_rec1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tab_rec1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 810, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AS_prod as=new AS_prod();
                
        String cat=(String)caty.getSelectedItem();
        as.Disp_InRecord(tab_rec1, cat);
        
        Call();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_prodActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_t_prodActionPerformed

    private void t_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_totalActionPerformed

    private void t_PUtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_PUtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_PUtotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> caty;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_PUtotal;
    private javax.swing.JTextField t_prod;
    private javax.swing.JTextField t_qty;
    private javax.swing.JTextField t_total;
    private javax.swing.JTable tab_rec1;
    // End of variables declaration//GEN-END:variables
}
